config/routes.rb
Rails.application.routes.draw do
    resources :boxes
    resources :recipes
  end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/box.rb
class Box < ApplicationRecord

# has_many :collections
# has_many :recipes, through: :collections

has_many :recipes
end

app/models/collection.rb
class Collection < ApplicationRecord
  belongs_to :box
  belongs_to :recipe
end

app/models/recipe.rb
class Recipe < ApplicationRecord

  # has_many :collections
  # has_many :boxes, through: :collections
  belongs_to :box

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/boxes_controller.rb
class BoxesController < ApplicationController


    def index
      @boxes = Box.all
    end

    def show
      @box = Box.find(params[:id])
    end

    def new
      @box = Box.new
    end

    def create
      @box = Box.create!(box_params)
      redirect_to @box
    end

    def edit
      @box = Box.find(params[:id])
    end

    def update
      @box = Box.find(params[:id])
      @box.update(box_params)
      redirect_to @box
    end

    def destroy
      @box = Box.find(params[:id])
      @box.destroy
      redirect_to boxes_path
    end

    private
    def box_params
      params.require(:box).permit(:title, :img_url, :motto, :house_id)
    end
  end
  

app/controllers/collections_controller.rb
class CollectionsController < ApplicationController
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController

    def index
      @recipes = Recipe.all
    end

    def show
      @recipe = Recipe.find(params[:id])
    end

    def new
      @recipe = Recipe.new
    end

    def create
      @recipe = Recipe.create!(recipe_params)
      redirect_to @recipe
    end

    def edit
      @recipe = Recipe.find(params[:id])
    end

    def update
      @recipe = Recipe.find(params[:id])
      @recipe.update(recipe_params)
      redirect_to @recipe
    end
# ***Double check redirect path***
    def destroy
      @recipe = Recipe.find(params[:id])
      @recipe.destroy
      redirect_to recipes_path

    end

    private
    def recipe_params
      params.require(:recipe).permit(:title, :img_url, :motto, :house_id)
    end
  end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/box_helper.rb
module BoxHelper
end

app/helpers/collection_helper.rb
module CollectionHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/box/index.html.erb
<div id="boxes" class="transitions-enabled">
  <% @boxes.each do |box| %>
  <div class="box">
    <%= link_to image_tag("#{box.img_url}"), box_path(box) %>
  </div>
    <% end %>
</div>

app/views/boxes/_box.html.erb
<li>
    <%= link_to box.name, box %> | <%= link_to 'Delete', box_path(box),
                                            method: :delete,
                                            data: { confirm: 'Are you sure?' } %>
</li>

app/views/boxes/_form.html.erb
<div class="form">
<% @box.errors.full_messages.each do |message| %>
<p>
  <%= message %>
</p>
<% end %>

<%= form_for @box do |f| %>
<h2>Create New box</h2>
<%= f.label :theme %>
<%= f.text_field :theme %>

  <%= f.label :title %>
  <%= f.text_field :title %>

  <%= f.label :img_url %>
  <%= f.text_field :img_url %>


  <%= f.submit %>
<% end %>
</div>

app/views/boxes/edit.html.erb
<h2>Edit <%= @box.title %></h2>
<%= link_to 'Delete', box_path(@box),
                                        method: :delete,
                                        data: { confirm: 'Are you sure?' } %>

<%= render 'form' %>

app/views/boxes/index.html.erb
<div id="boxes" class="transitions-enabled">
  <% @boxes.each do |box| %>
  <%= box.title %>
  <div class="box">
    <%= link_to image_tag("#{box.img_url}"), box_path(box) %>
  </div>
    <% end %>
</div>

app/views/boxes/new.html.erb
<div class="whitespace"></div>


<%= render 'form' %>

app/views/boxes/show.html.erb
<% flash.each do |type, message| %>
  <p><%= type %>: <%= message %></p>
<% end %>
<div class="whitespace"></div>
<div class="box-profile">
<h2>
  <%= @box.title %>
  <h2>
  <h3><%= link_to "Edit", edit_box_path(@box) %>
  <%= link_to "Delete", box_path(@box),
                                        method: :delete,
                                        data: { confirm: 'Are you sure?' } %></h3>

<hr>
<div class="boxes">
<img class="recipe-box" src="<%= @box.img_url %>">
</div>
<p>Box Theme:</p><h4><%= @box.theme %></h4>

<div>
<h4> insert recipe image here<h4>
</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Food.Me</title>
  </head>
  <body>

    <%= yield %>

  </body>
</html>

app/views/recipes/_form.html.erb
<div class="form">
<%= form_for @recipe do |f| %>
<h2>Create New Character</h2>
  <%= f.label :name %>
  <%= f.text_field :name %>



  <%= f.select( :house_id, House.all.collect { |house| [house.name, house.id] } ) %>

  <%= f.label :img_url %>
  <%= f.text_field :img_url %>


  <%= f.submit %>
<% end %>
</div>

app/views/recipes/edit.html.erb
<h2>Edit <%= @recipe.name %></h2>
<%= link_to 'Delete', recipe_path(@recipe),
                                              method: :delete,
                                              data: { confirm: 'Are you sure?' } %>



<%= render 'form'  %>

app/views/recipes/index.html.erb
<div class="whitespace"></div>
<div id="people" class="transitions-enabled">
  <% @recipes.each do |recipe| %>
  <div class="box">
<%= link_to image_tag("#{recipe.img_url}"), recipe_path(recipe) %>
</div>
  <% end %>
</div>

app/views/recipes/new.html.erb
<hi>New Recipe</hi>
<%= render 'form' %>
<br/>
<%= link_to "Back", recipes_path, class: "btn-default" %>

app/views/recipes/show.html.erb
<% flash.each do |type, message| %>
  <p><%= type %>: <%= message %></p>
<% end %>

<div class="whitespace"></div>
<div class="recipe-profile">
<h1>Name: <%= @recipe.name %></h1>
<h3>
  <%= link_to "(edit)", edit_recipe_path(@recipe) %> |
  <%= link_to 'Delete', recipe_path(@recipe),
                                                method: :delete,
                                                data: { confirm: 'Are you sure?' } %>
</h3>
<hr>
<img src="<%= @recipe.img_url %>">


<h2>House: <%= @recipe.house_id %></h2>
<h2>Biograhpy:</h2>
</div>